---
abstract: 'SSL in a filter'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Transform::SSL
name: Data-Transform-SSL
no_index:
  directory:
    - inc
    - t
provides:
  Data::Transform::SSL:
    file: lib/Data/Transform/SSL.pm
    version: 0.03
requires:
  Carp: 0
  Data::Transform: 0.05_01
  Net::SSLeay: 1.30
  POE: 0
  perl: 5.6.0
version: 0.03
